server:
  # 应用端口号
  port: 8081

spring:
  application:
    # 应用名称
    name: config-server
  cloud:
    config:
      server:
        git:
          # 配置git仓库位置
          uri: https://github.com/Linxichun/my-test.git
          # 配置仓库路径下的相对搜索位置，多个中间逗号隔开
          search-paths: /client-config
          # 访问git仓库的用户名
          username:
          # 访问git仓库的用户密码
          password:
          default-label: master
        default-label: develop
